AWSTemplateFormatVersion: '2010-09-09'
Description: 'Course Registration Infrastructure'

Resources:
  CourseRegistrationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: course-registrations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: production
        - Key: Application
          Value: course-registration

Outputs:
  TableName:
    Description: 'DynamoDB Table Name'
    Value: !Ref CourseRegistrationsTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'
  
  TableArn:
    Description: 'DynamoDB Table ARN'
    Value: !GetAtt CourseRegistrationsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'